[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc'

    [plugins.build]
    windows = 'tools\\update-dll-mingw'
    cygwin  = 'make -f make_cygwin.mak'
    mac     = 'make'
    linux   = 'make'
    unix    = 'gmake'

# スニペット
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tmhedberg/matchit'

# NERDTree
[[plugins]]
repo = 'scrooloose/nerdtree'

# make時のエラーマーカー表示
[[plugins]]
repo = 'errormarker.vim'

# インデントに色を付けて見やすくする
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# 置換ハイライト
[[plugins]]
repo = 'osyo-manga/vim-over'

# 行末の半角スペースを可視化
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# molokai カラースキーム
[[plugins]]
repo = 'tomasr/molokai'

# 囲いを簡易化
[[plugins]]
repo = 'tpope/vim-surround'

# editorconfig有効化
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

# ファイル操作快適化
[[plugins]]
repo = 'Shougo/unite.vim'

# Unite.vimで最近使ったファイルを表示
[[plugins]]
repo = 'Shougo/neomru.vim'

# ログファイルを色づけしてくれる
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

# ステータスライン表示
[[plugins]]
repo = 'itchyny/lightline.vim'

# Vim上でGit
[[plugins]]
repo = 'tpope/vim-fugitive'
