# 括弧自動補完
[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

# キャッシュを備えた自動補完機能
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1
'''



'''


[[plugins]]

# HTML5文法チェック
[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html','smarty']
