# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

# Markdown Preview
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_source = '''
  autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} set filetype=markdown
  let g:vim_markdown_folding_disabled=1
'''

# Markdown Preview
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
hook_source = '''
  let g:previm_show_header=0
  let g:previm_custom_css_path='~/.vim/templates/previm/markdown.css'
  autocmd BufNewFile,BufRead *.{md,mdwn,mkd,mkdn,mark*} :Previm
'''
