# 括弧自動補完
[[plugins]]
repo = 'Townk/vim-autoclose'
on_i = 1

# キャッシュを備えた自動補完機能
[[plugins]]
repo = 'Shougo/neocomplete.vim'
on_i = 1

# コードスニペット
[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# HTML,CSSコーディング
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','smarty','css']

# HTML5文法チェック
[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft = ['html','smarty']

# javascript用syntax
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# css3用syntax
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

# Go用syntax
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

# Markdown Preview
[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown']

# Markdown Preview
[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']
